[package]
name = "testingForRust"
version = "0.1.0"
authors = ["Brianna Swanson <briannas228@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5" #changes frequenty, consider keeping an eye out